apiVersion: batch/v1

kind: Job

metadata:
  name: math-add-job

spec:
  completions: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: math-add
          image: ubuntu:20.04
          command: ["expr", "3", "+", "2"]
