apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data
  # options instead of hostPath
  awsElasticBlockStore:
    volumeID: volID
    fsType: ext4
  persistentVolumeReclaimPolicy: Recycle # Delete or Retain
