apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp

spec:
  containers:
    - name: nginx-containers
      image: nginx
      envFrom:
        - secretRef:
            name: nginx-secret
      env:
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_Password
      volumes:
        - name: app-secret-volume
          secret:
            secretName: app-secret
