apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod

spec:
  containers:
    - name: nginx-containers
      image: nginx
  serviceAccountName: serviceAccountName
  automountServiceAccountToken: false
